---
# This role deploys the mongodb processes and sets up settings.

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

