---
# graylog2 

- src: graylog2.graylog
  version: master

# graylog2 dependency

- src: lesmyrmidons.mongodb
  version: master

- src: geerlingguy.java
  version: master

# 0.2 is required version to use elasticsearch 2.x
- src: elastic.elasticsearch
  version: "0.2"

- src: jdauphant.nginx
  version: master

