---
# defaults file for fluentd
fluentd_master_image: supernova106/fluentd-agent
fluentd_master_tag: latest
elasticsearch_host: localhost
elasticsearch_port: 443

supervisord_conf_dir: /etc/supervisord
supervisord_exec_dir: /usr/local/bin
customized_bin_dir: /opt/bin

elasticsearch_conf_dir: /etc/elasticsearch

# fluentd agent
fluentd_master_host: localhost
fluentd_master_port: 24224
path_to_log_dir: #/var/log/app/
log_name: #error.log
app_name: rz_app
regex_format: /^(?<user_ip>[\d\.]*).*\[(?<time>[^\[]*)\]\s\"(?<request>[^\"]*)\"\s(?<code>[\d]*)\s.*\s\d*\s\"(?<apiname>[^\"]*)\"\s\"(?<backend>.*)\"\s(?<request_time>.*)ms$/